name=ESP32 HUB75 LED MATRIX PANEL DMA Display
version= 0.0.1
author=Ocram72NL
maintainer=Ocram72NL
sentence=FM6363 HUB75 LED Matrix Library for ESP32-S3
paragraph=An Adafruit GFX compatible library for FM6353 LED matrix modules which uses DMA to control the HUB75 signals.
category=Display
url=https://github.com/ocram72nl/ESP32-HUB75-MatrixPanel-DMA-FM6363
architectures=esp32s3